/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events.index'
import { Route as AuthenticatedEventsCreateRouteImport } from './routes/_authenticated/events.create'
import { Route as AuthenticatedEventsSavedRouteImport } from './routes/_authenticated/events.saved'
import { Route as AuthenticatedLostFoundIndexRouteImport } from './routes/_authenticated/lost-found.index'
import { Route as AuthenticatedLostFoundIdRouteImport } from './routes/_authenticated/lost-found.$id'
import { Route as AuthenticatedLostFoundCreateRouteImport } from './routes/_authenticated/lost-found.create'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedProfileChangePasswordRouteImport } from './routes/_authenticated/profile.change-password'
import { Route as AuthenticatedResourcesIndexRouteImport } from './routes/_authenticated/resources.index'
import { Route as AuthenticatedResourcesIdRouteImport } from './routes/_authenticated/resources.$id'
import { Route as AuthenticatedResourcesUploadRouteImport } from './routes/_authenticated/resources.upload'
import { Route as AuthenticatedSharingIndexRouteImport } from './routes/_authenticated/sharing.index'
import { Route as AuthenticatedSharingCreateRouteImport } from './routes/_authenticated/sharing.create'
import { Route as AuthenticatedEventsIdIndexRouteImport } from './routes/_authenticated/events.$id.index'
import { Route as AuthenticatedEventsIdEditRouteImport } from './routes/_authenticated/events.$id.edit'
import { Route as AuthenticatedSharingIdIndexRouteImport } from './routes/_authenticated/sharing.$id.index'
import { Route as AuthenticatedSharingIdEditRouteImport } from './routes/_authenticated/sharing.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsCreateRoute =
  AuthenticatedEventsCreateRouteImport.update({
    id: '/events/create',
    path: '/events/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsSavedRoute =
  AuthenticatedEventsSavedRouteImport.update({
    id: '/events/saved',
    path: '/events/saved',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLostFoundIndexRoute =
  AuthenticatedLostFoundIndexRouteImport.update({
    id: '/lost-found/',
    path: '/lost-found/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLostFoundIdRoute =
  AuthenticatedLostFoundIdRouteImport.update({
    id: '/lost-found/$id',
    path: '/lost-found/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLostFoundCreateRoute =
  AuthenticatedLostFoundCreateRouteImport.update({
    id: '/lost-found/create',
    path: '/lost-found/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileChangePasswordRoute =
  AuthenticatedProfileChangePasswordRouteImport.update({
    id: '/profile/change-password',
    path: '/profile/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourcesIndexRoute =
  AuthenticatedResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourcesIdRoute =
  AuthenticatedResourcesIdRouteImport.update({
    id: '/resources/$id',
    path: '/resources/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourcesUploadRoute =
  AuthenticatedResourcesUploadRouteImport.update({
    id: '/resources/upload',
    path: '/resources/upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSharingIndexRoute =
  AuthenticatedSharingIndexRouteImport.update({
    id: '/sharing/',
    path: '/sharing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSharingCreateRoute =
  AuthenticatedSharingCreateRouteImport.update({
    id: '/sharing/create',
    path: '/sharing/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdIndexRoute =
  AuthenticatedEventsIdIndexRouteImport.update({
    id: '/events/$id/',
    path: '/events/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdEditRoute =
  AuthenticatedEventsIdEditRouteImport.update({
    id: '/events/$id/edit',
    path: '/events/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSharingIdIndexRoute =
  AuthenticatedSharingIdIndexRouteImport.update({
    id: '/sharing/$id/',
    path: '/sharing/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSharingIdEditRoute =
  AuthenticatedSharingIdEditRouteImport.update({
    id: '/sharing/$id/edit',
    path: '/sharing/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/events/saved': typeof AuthenticatedEventsSavedRoute
  '/lost-found/$id': typeof AuthenticatedLostFoundIdRoute
  '/lost-found/create': typeof AuthenticatedLostFoundCreateRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/profile/change-password': typeof AuthenticatedProfileChangePasswordRoute
  '/resources/$id': typeof AuthenticatedResourcesIdRoute
  '/resources/upload': typeof AuthenticatedResourcesUploadRoute
  '/sharing/create': typeof AuthenticatedSharingCreateRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/lost-found/': typeof AuthenticatedLostFoundIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/resources/': typeof AuthenticatedResourcesIndexRoute
  '/sharing/': typeof AuthenticatedSharingIndexRoute
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/sharing/$id/edit': typeof AuthenticatedSharingIdEditRoute
  '/events/$id/': typeof AuthenticatedEventsIdIndexRoute
  '/sharing/$id/': typeof AuthenticatedSharingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/events/saved': typeof AuthenticatedEventsSavedRoute
  '/lost-found/$id': typeof AuthenticatedLostFoundIdRoute
  '/lost-found/create': typeof AuthenticatedLostFoundCreateRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/profile/change-password': typeof AuthenticatedProfileChangePasswordRoute
  '/resources/$id': typeof AuthenticatedResourcesIdRoute
  '/resources/upload': typeof AuthenticatedResourcesUploadRoute
  '/sharing/create': typeof AuthenticatedSharingCreateRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/lost-found': typeof AuthenticatedLostFoundIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/resources': typeof AuthenticatedResourcesIndexRoute
  '/sharing': typeof AuthenticatedSharingIndexRoute
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/sharing/$id/edit': typeof AuthenticatedSharingIdEditRoute
  '/events/$id': typeof AuthenticatedEventsIdIndexRoute
  '/sharing/$id': typeof AuthenticatedSharingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/events/create': typeof AuthenticatedEventsCreateRoute
  '/_authenticated/events/saved': typeof AuthenticatedEventsSavedRoute
  '/_authenticated/lost-found/$id': typeof AuthenticatedLostFoundIdRoute
  '/_authenticated/lost-found/create': typeof AuthenticatedLostFoundCreateRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/profile/change-password': typeof AuthenticatedProfileChangePasswordRoute
  '/_authenticated/resources/$id': typeof AuthenticatedResourcesIdRoute
  '/_authenticated/resources/upload': typeof AuthenticatedResourcesUploadRoute
  '/_authenticated/sharing/create': typeof AuthenticatedSharingCreateRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/lost-found/': typeof AuthenticatedLostFoundIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/resources/': typeof AuthenticatedResourcesIndexRoute
  '/_authenticated/sharing/': typeof AuthenticatedSharingIndexRoute
  '/_authenticated/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/_authenticated/sharing/$id/edit': typeof AuthenticatedSharingIdEditRoute
  '/_authenticated/events/$id/': typeof AuthenticatedEventsIdIndexRoute
  '/_authenticated/sharing/$id/': typeof AuthenticatedSharingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/home'
    | '/events/create'
    | '/events/saved'
    | '/lost-found/$id'
    | '/lost-found/create'
    | '/messages/$conversationId'
    | '/profile/change-password'
    | '/resources/$id'
    | '/resources/upload'
    | '/sharing/create'
    | '/events/'
    | '/lost-found/'
    | '/messages/'
    | '/profile/'
    | '/resources/'
    | '/sharing/'
    | '/events/$id/edit'
    | '/sharing/$id/edit'
    | '/events/$id/'
    | '/sharing/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/home'
    | '/events/create'
    | '/events/saved'
    | '/lost-found/$id'
    | '/lost-found/create'
    | '/messages/$conversationId'
    | '/profile/change-password'
    | '/resources/$id'
    | '/resources/upload'
    | '/sharing/create'
    | '/events'
    | '/lost-found'
    | '/messages'
    | '/profile'
    | '/resources'
    | '/sharing'
    | '/events/$id/edit'
    | '/sharing/$id/edit'
    | '/events/$id'
    | '/sharing/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/home'
    | '/_authenticated/events/create'
    | '/_authenticated/events/saved'
    | '/_authenticated/lost-found/$id'
    | '/_authenticated/lost-found/create'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/profile/change-password'
    | '/_authenticated/resources/$id'
    | '/_authenticated/resources/upload'
    | '/_authenticated/sharing/create'
    | '/_authenticated/events/'
    | '/_authenticated/lost-found/'
    | '/_authenticated/messages/'
    | '/_authenticated/profile/'
    | '/_authenticated/resources/'
    | '/_authenticated/sharing/'
    | '/_authenticated/events/$id/edit'
    | '/_authenticated/sharing/$id/edit'
    | '/_authenticated/events/$id/'
    | '/_authenticated/sharing/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/create': {
      id: '/_authenticated/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof AuthenticatedEventsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/saved': {
      id: '/_authenticated/events/saved'
      path: '/events/saved'
      fullPath: '/events/saved'
      preLoaderRoute: typeof AuthenticatedEventsSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lost-found/': {
      id: '/_authenticated/lost-found/'
      path: '/lost-found'
      fullPath: '/lost-found/'
      preLoaderRoute: typeof AuthenticatedLostFoundIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lost-found/$id': {
      id: '/_authenticated/lost-found/$id'
      path: '/lost-found/$id'
      fullPath: '/lost-found/$id'
      preLoaderRoute: typeof AuthenticatedLostFoundIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lost-found/create': {
      id: '/_authenticated/lost-found/create'
      path: '/lost-found/create'
      fullPath: '/lost-found/create'
      preLoaderRoute: typeof AuthenticatedLostFoundCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/change-password': {
      id: '/_authenticated/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof AuthenticatedProfileChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources/': {
      id: '/_authenticated/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AuthenticatedResourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources/$id': {
      id: '/_authenticated/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof AuthenticatedResourcesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources/upload': {
      id: '/_authenticated/resources/upload'
      path: '/resources/upload'
      fullPath: '/resources/upload'
      preLoaderRoute: typeof AuthenticatedResourcesUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sharing/': {
      id: '/_authenticated/sharing/'
      path: '/sharing'
      fullPath: '/sharing/'
      preLoaderRoute: typeof AuthenticatedSharingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sharing/create': {
      id: '/_authenticated/sharing/create'
      path: '/sharing/create'
      fullPath: '/sharing/create'
      preLoaderRoute: typeof AuthenticatedSharingCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/': {
      id: '/_authenticated/events/$id/'
      path: '/events/$id'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof AuthenticatedEventsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/edit': {
      id: '/_authenticated/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof AuthenticatedEventsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sharing/$id/': {
      id: '/_authenticated/sharing/$id/'
      path: '/sharing/$id'
      fullPath: '/sharing/$id/'
      preLoaderRoute: typeof AuthenticatedSharingIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sharing/$id/edit': {
      id: '/_authenticated/sharing/$id/edit'
      path: '/sharing/$id/edit'
      fullPath: '/sharing/$id/edit'
      preLoaderRoute: typeof AuthenticatedSharingIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedEventsCreateRoute: typeof AuthenticatedEventsCreateRoute
  AuthenticatedEventsSavedRoute: typeof AuthenticatedEventsSavedRoute
  AuthenticatedLostFoundIdRoute: typeof AuthenticatedLostFoundIdRoute
  AuthenticatedLostFoundCreateRoute: typeof AuthenticatedLostFoundCreateRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedProfileChangePasswordRoute: typeof AuthenticatedProfileChangePasswordRoute
  AuthenticatedResourcesIdRoute: typeof AuthenticatedResourcesIdRoute
  AuthenticatedResourcesUploadRoute: typeof AuthenticatedResourcesUploadRoute
  AuthenticatedSharingCreateRoute: typeof AuthenticatedSharingCreateRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedLostFoundIndexRoute: typeof AuthenticatedLostFoundIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedResourcesIndexRoute: typeof AuthenticatedResourcesIndexRoute
  AuthenticatedSharingIndexRoute: typeof AuthenticatedSharingIndexRoute
  AuthenticatedEventsIdEditRoute: typeof AuthenticatedEventsIdEditRoute
  AuthenticatedSharingIdEditRoute: typeof AuthenticatedSharingIdEditRoute
  AuthenticatedEventsIdIndexRoute: typeof AuthenticatedEventsIdIndexRoute
  AuthenticatedSharingIdIndexRoute: typeof AuthenticatedSharingIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedEventsCreateRoute: AuthenticatedEventsCreateRoute,
  AuthenticatedEventsSavedRoute: AuthenticatedEventsSavedRoute,
  AuthenticatedLostFoundIdRoute: AuthenticatedLostFoundIdRoute,
  AuthenticatedLostFoundCreateRoute: AuthenticatedLostFoundCreateRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedProfileChangePasswordRoute:
    AuthenticatedProfileChangePasswordRoute,
  AuthenticatedResourcesIdRoute: AuthenticatedResourcesIdRoute,
  AuthenticatedResourcesUploadRoute: AuthenticatedResourcesUploadRoute,
  AuthenticatedSharingCreateRoute: AuthenticatedSharingCreateRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedLostFoundIndexRoute: AuthenticatedLostFoundIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedResourcesIndexRoute: AuthenticatedResourcesIndexRoute,
  AuthenticatedSharingIndexRoute: AuthenticatedSharingIndexRoute,
  AuthenticatedEventsIdEditRoute: AuthenticatedEventsIdEditRoute,
  AuthenticatedSharingIdEditRoute: AuthenticatedSharingIdEditRoute,
  AuthenticatedEventsIdIndexRoute: AuthenticatedEventsIdIndexRoute,
  AuthenticatedSharingIdIndexRoute: AuthenticatedSharingIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
